# this workflow's name
name: Release

# Runs on published releases
on: 
  release:
    types: [published]

# jobs to run on this workflow
jobs:
  # build job
  release:
    # the base image where the job is run
    runs-on: windows-2019

    # this job's steps
    steps:
    # check out this repository to be used in the following steps
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1

    # parse semver
    - name: Retrieve release version
      id: parse-semver
      uses: booxmedialtd/ws-action-parse-semver@v1
      with:
        input_string: ${{ github.ref }}
        version_extractor_regex: '\/v(.*)$'

    # create nuget packages
    - name: Pack
      env:
        semver: ${{ steps.parse-semver.outputs.fullversion }}
      run: dotnet pack ./GitHubPackage -c Release -o packages -p:Version=$env:semver
    
    # push
    - name: Publish to Package Registry
      run: dotnet nuget push packages\**\*.nupkg --source "github"